server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.84:8761/eureka/

spring:
  application:
    name: mycloud-eureka-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: mycloud-eureka-consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: mycloud-eureka-consumer-feign